name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone Repository
        uses: actions/checkout@v2

      - name: 🔧 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: 📦 Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3-pip openjdk-17-jdk
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: 🔨 Build APK
        run: |
          buildozer -v android debug

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: FootballApp
          path: bin/*.apk
